# Generated by Django 5.2.17 on 2026-09-28 15:20

import photos.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', validators=[photos.validator.FileSizeValidator(5)])),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=30)),
                ('date_of_publication', models.DateField(auto_now=True)),
                ('tag_pets', models.ManyToManyField(to='pets.pet')),
            ],
        ),
    ]
